vrrp_instance VI_PXE {
    state MASTER
    interface ens18        
    virtual_router_id 66  
    priority 100           
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass PxeHA2026
    }
    virtual_ipaddress {
        10.30.30.200
    }
}
